#!/bin/bash
# Launch jcutecom (cutecom with telnet support created by Jon Thompson)

image=docker.io/leehudsondls/cutecom-qt3
version=latest
hostname=$(hostname)
pull=false
delete=false
gui=false
network="--net=host"
container_name=cutecom-qt3

while getopts "lrdpghs:i:v:n" arg; do
    case $arg in
        l) set -x ;;  # enable logging
        r) userns="" ;;  # run as root
        g) gui=true ;;
        p) pull=true ;;
        s) hostname=$OPTARG ;;
        i) image=$OPTARG ;;
        v) version=$OPTARG ;;
        n) network="--network=podman" ;;
        d) delete=true ;;
        *) echo "Usage: $0 [-l] [-r] [-g] [-p] [-s hostname] [-i image] [-v version] [-n] [-d]"; exit 0 ;;
    esac
done
shift $((OPTIND-1))

# Prevent running inside a devcontainer
if [[ -e /etc/centos-release ]]; then
    echo "ERROR: already in a devcontainer"
    exit 1
fi

# Delete old container if requested
if $delete; then
    podman rm -ft0 $container_name
fi

# Pull image if needed
if ! podman image exists ${image}:${version} || $pull; then
    podman pull ${image}:${version}
fi

# Environment variables
environ="
    -e CONTAINER_NAME=${container_name}
    -e DISPLAY
    -e HOME
    -e USER
    -e SSH_AUTH_SOCK
    -e TERM=xterm-256color
"

# Volumes
volumes="-v /home:/home:shared"

# Options
opts="${network} --hostname ${hostname} --security-opt=label=disable"

# X11 GUI setup
if [[ $gui == "true" ]]; then
    XSOCK=/tmp/.X11-unix
    XAUTH=/tmp/.container.xauth.$USER
    touch $XAUTH
    xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
    chmod 777 $XAUTH
    x11="-v $XAUTH:$XAUTH -e XAUTHORITY=$XAUTH"
    opts="${opts} ${x11}"
    echo "X11 over SSH compatibility enabled"
fi

# Runtime
runtime=""
if which crun &> /dev/null; then
    runtime="--runtime /usr/bin/crun"
    identity="--annotation run.oci.keep_original_groups=1 --storage-opt ignore_chown_errors=true"
else
    identity="--annotation run.oci.keep_original_groups=1"
fi

# Start or attach to container
if [[ -n $(podman ps -q -f name=${container_name}) ]]; then
    echo "Attaching to existing container..."
elif [[ -n $(podman ps -qa -f name=${container_name}) ]]; then
    echo "Restarting stopped container..."
    podman start ${container_name}
else
    echo "Creating new container..."
    podman run -dit --name ${container_name} ${runtime} ${environ} ${identity} ${volumes} ${opts} ${image}:${version}
fi
